# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/staticli/staticli/lib.Version={{.Version}} -X github.com/staticli/staticli/lib.BuildCommit={{.ShortCommit}} -X github.com/staticli/staticli/lib.BuildTime={{.Date}} -X github.com/staticli/staticli/lib.BuildRepo={{.GitURL}}
#archive:
#  format: binary
#  name_template: "{{ .ProjectName }}.{{ .Os }}.{{ .Arch }}"
archives:
  - name_template: "{{ .ProjectName }}.{{ .Os }}.{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'