language: C
sudo: required

services:
  - docker
stages:
  - name: after_success
    if: branch = master
script:
  - make -j2 && make test-binary
deploy:
  provider: script
  script: make release
  on:
    branch: master